### ISSUE TITLE
Support for numerically-differentiated calculations

### ISSUE THREAD

**Issue by ddhendriks** [NIFTy-PPL/JAXbind#14]
LS,

In my project, I found the need to implement numerical differentiation support in pytorch. Is it on the roadmap to provide that for this tool too? I might be able to add this myself and provide a PR.

**Comment by roth-jakob** [comment]
Thanks for your interest in JAXbind!

Finite differences numerical differentiation is not on our roadmap. I am also not entirely sure if one can implement it in a way that is usable for a broader range of applications. Can you give us an idea of your use case and how you would implement it?

**Comment by ddhendriks** [comment]
Hi. 

So in my use-case I want to include likelihoods that are not easy to make differentiable because the actual calculation is done in a different code (e.g. some C-based code where implementing autodifferentiable calculations is just not feasible), through some c-binding for example. I do, however, want to be able to have a framework like (num)pyro, be able to handle these likelihoods by using a fallback numerical differentiation technique, so the entire chain of calculations (including other, autodifferentiable, parts) can just be handled in that framework.

Now I'm not sure if it is indeed within the scope of this project, but the scope/name suggested that this project provides jax-based differentiability for any function. 

It may be relatively easy as there are already solutions for JAX (e.g. [https://github.com/google/jax/issues/15425#issuecomment-1576803618](https://github.com/google/jax/issues/15425#issuecomment-1576803618)), and in pytorch I use a wrapper that handles this ([see this script](https://gitlab.com/dhendriks/project_hmc/-/blob/main/hmc_project_code/functions/finite_diff_functionality/finite_diff_decorator.py?ref_type=heads).

Hope that clarifies the use-case!

**Comment by roth-jakob** [comment]
Thanks for clarifying! This is not the primary core scope of the JAXbind package, as we focus on binding functions implemented in other programming languages to JAX rather than on numerical differentiation techniques.

Nevertheless, I believe JAXbind might be useful for you. Specifically, once you have a routine for computing the numerical derivative of your function, you could use JAXbind to connect the numerical derivatives with the JAX automatic differentiation backend. A good starting point for you could be [demo_03](https://nifty-ppl.github.io/JAXbind/demos/03_nonlinear_function.html). This demo binds a nonlinear function with an analytic derivative to JAX. For your case, you need to replace the function evaluating the analytic derivative with your numeric differentiation derivative.

If you run into any problems with JAXbind or have any questions about It, feel free to ask us!

**Comment by roth-jakob** [comment]
I will close this issue now. If you have any questions feel free to reopen or open a new issue
